package com.suadh.code401taskmaster.taskmasterapp;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

@DynamoDBTable(tableName = "taskmaster")
    public class Taskmaster {

    private UUID  taskId;
    private String description;
    private String title;
    private String status;


    public Taskmaster() {

    }

    public Taskmaster(String title, String description, String status) {
        this.title = title;
        this.description = description;
        this.status = "Availabe";
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID  getTaskId() {
        return taskId;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setTaskId(UUID taskId) {
        this.taskId = taskId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
